apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: zag91jcnb-go 
  janus-idp.io/tekton: zag91jcnb-go
  backstage.io/kubernetes-id: zag91jcnb-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: zag91jcnb-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  